### PR TITLE
Sc hab descriptors

### PR DESCRIPTION
**Pull request by stephencastaneda**
# Description
I added habitat descriptor characteristics.
Fixes # (issue)
## Type of change
Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)
# Testing Instructions
Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings or errors

### CODE REVIEW

**Comment by ghost** [comment]
Looks good!

**Comment by BrianCravens** [comment]
Looks Good to me matey!

**Review by AdiGarmendia — APPROVED** [review]
Checked in branch, looks good

**Comment by tstrotherIV** [comment]
:shipit:

**Review by ghost — APPROVED** [review]

**Review by BrianCravens — APPROVED** [review]

**Review by tstrotherIV — APPROVED** [review]

**Pull request merged**
