### PR TITLE
Adi start

### PR DESCRIPTION
**Pull request by AdiGarmendia**
# Description
Created the environment class and got it working with river and annex
Fixes # (issue)
## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
# Testing Instructions
check into adi-start branch and run index.py. annex a river and then run the report
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by stephencastaneda — APPROVED** [review]
I got a rivuhhhh

**Review by tstrotherIV — APPROVED** [review]
IT WORKS!

**Review by ghost — APPROVED** [review]
Sweet! Got a river!

**Review by BrianCravens — APPROVED** [review]
Pulled down and looks good

**Pull request merged**
